server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3009/loki/api/v1/push

scrape_configs:
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:1514
      idle_timeout: 60s
      label_structured_data: yes
      labels:
        job: "syslog"
    relabel_configs:
      - source_labels: ["__syslog_message_hostname"]
        target_label: "host"
    pipeline_stages:
      - match:
          selector: '{job="syslog"}'
          stages:
            - regex:
                expression: 'SRC=(?P<src_ip>\d+\.\d+\.\d+\.\d+)\s+DST=(?P<dest_ip>\d+\.\d+\.\d+\.\d+)'
            - labels:
                src_ip:
                dest_ip:
